version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/metrics_db
    ports:
      - "6000:6000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
